### DISCUSSION TITLE
MonoApi construct

### DISCUSSION THREAD

**Discussion by piolet** [getlift/lift#181] [Constructs]
To go with this great news (https://www.serverless.com/blog/aws-lambda-function-urls-with-serverless-framework) 
The idea would be to create a constructor that uses the url created by the serverless framework by linking it to a CDN.
With the CDN, you could create a domain and have a complete template.

This constructor would take as argument the arn of a certificate, the name of the domain to create and the reference to the Lambda or its URL.

```
service: my-api

provider:
    name: aws

plugins:
    - serverless-lift

functions:
    myFunction:
        handler: handler.hello
        # This URL is protected by IAM authentication
        url:
          authorizer: aws_iam

constructs:
    my_api:
        type: mono-api
        domain: api.example.com
        certificat: arn:...
        functionUrl: ${myFunction ref url}
```
For the moment, I don't know if the CDK allows to have this information concerning the Lambda and its URL.

For opinion, and also for a little help ;)

**Comment by t-richard** [comment]
I like the idea 👍

Not sure about the construct name but that's a detail 😊

I'm wondering if we can factor some things with the server-side website construct or even merge the two? 
Those are similar in some way and we could even imagine a server-side website plugged to a mono lambda with a function url.

**Comment by piolet** [comment]
When starting my implementation, I found a lot of things to recover from the server-side website actually.

Concerning the idea you mention, it would be in line with the future presentation of @mnapoli  (https://twitter.com/matthieunapoli/status/1512023467100626950)

But how to work with the reference of the lambda or its url. Does the serverless framework give these informations ? 

And for the name... i agree with you :D

**Comment by fredericbarthelet** [comment]
Thanks for this proposal @piolet :) !

In order to have an "autonomous" construct, I'd suggest a definition interface similar to queue construct, where a lambda is involved as well.

WDYT ?

**Reply by piolet** [reply]
I'll look into it.
I haven't watched that other construct yet (queue)

**Reply by mnapoli** [reply]
+1 on the idea, maybe something like this:

```yaml
constructs:
    api:
        type: mono-lambda-api
        function:
            handler: index.handler
            memory: 512
            ...
        domain: api.example.com
        certificate: arn:...
```

But then I wonder: is this for creating APIs, or for websites? Should we include assets in there?

Because we could make _anything_, but what is the construct that will actually be useful out there 🤔  And that I'm not sure.
