### DISCUSSION TITLE
Make public bucket

### DISCUSSION THREAD

**Discussion by kevincerro** [getlift/lift#201] [Constructs]
As docs says: 
[By default, all the Lambda functions deployed in the same serverless.yml file will be allowed to read/write into the bucket.](https://github.com/getlift/lift/blob/master/docs/storage.md#permissions)

**¿What if you need to make these resources publicly accessible?**
Imagine that users can upload a profile picture and others must have access to view these profile pictures.
One solution can be generating presignedUrls but at this moment I cannot implement this.

This is what I do without lift in other projects:
```
resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:custom.AppBucketName}'
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - 'https://${self:custom.domain.current}'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
    AppBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref AppBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - 's3:GetObject'
              Resource: !Join [ '/', [ !GetAtt AppBucket.Arn, '*' ] ]
```

¿Is possible to archive this with current lift implementation?

With lift I do:
```
constructs:
    uploads:
        type: storage
```
