### DISCUSSION TITLE
Get default origin cloudfront

### DISCUSSION THREAD

**Discussion by artgoce** [getlift/lift#226] [Constructs]
Is there any way we can get the default origin that lift creates at Cloudfront? I'm trying to define some CacheBehaviors without defining my own origin and S3 definition.

```
my-app:
    type: single-page-app
    path: 'dist/my-app'
    extensions:
      distribution:
        Properties:
          DistributionConfig:
            DefaultCacheBehavior:
              ResponseHeadersPolicyId:
                Ref: ResponseHeadersPolicyCORS
            CacheBehaviors:
            - PathPattern: '/some-file.json'
              TargetOriginId: "********"
              CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
              ResponseHeadersPolicyId:
                Ref: ResponseHeadersPolicyNoCache
              ViewerProtocolPolicy: 'redirect-to-https'
           
```
