### DISCUSSION TITLE
How to reference table to event?

### DISCUSSION THREAD

**Discussion by richard457** [getlift/lift#281] [Constructs]
Hi, I used to reference table like this 
```
EVENT:
    handler: EVENT.handler
    tracing: "false"
    events:
      - stream:
          type: "dynamodb"
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Table
              - StreamArn
          filterPatterns:
            - eventName: [INSERT]
         ``` 
but now I want to reference table in Fn::GetAtt: generated by construct how can I do that?
