### DISCUSSION TITLE
Adding SimpleCORS Policy to CloudFront Distribution

### DISCUSSION THREAD

**Discussion by whobutsb** [getlift/lift#338] [Constructs]
Hello all!  Would someone be able to give me a suggestion on the best way to add the Response headers policy `SimpleCORS` policy to my CloudFront distribution in my `serverless.yml` during deployment? Currently I'am manually adding it to my distribution but for ease of deployment it would be great to have it set.  I know you can do it in the `constructs.extensions` array, but just need a hint.  

Here is what I currently have: 
```
constructs:
  website:
    type: server-side-website
    assets:
      '/build/*': public/build
```

I appreciate the help!
