### DISCUSSION TITLE
How to use !Ref or Fn:GetAtt in lift models

### DISCUSSION THREAD

**Discussion by cmcnicholas** [getlift/lift#345] [Constructs]
Hi, I have opened a PR with support for queue subscriptions here: https://github.com/getlift/lift/pull/344

But does anyone know how to use `!Ref` declarations with the lift models and/or CDK? I can't find any examples in this repo but essentially I would like to alter the code so it doesn't require an ARN but can depend on another serverless resource, e.g.

```yaml
resources:
  Resources:
    MyTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: SuperTopic

constructs:
  my-queue:
    type: queue
    worker:
      handler: worker.handler
    subscriptions:
      - topic: !Ref MyTopic # this doesn't work
```

is there examples out there of how this is achieved either within lift or separate plugins?

**Comment by cmcnicholas** [comment]
OK further to the above I have managed to get the following to work:

```ts
const fn = Fn.getAtt("MyTopic", "TopicArn");
const topic = Topic.fromTopicArn(this, "SomeId", fn.toString());
topic.addSubscription(new SqsSubscription(this.queue, { filterPolicy, rawMessageDelivery: true }));
```

if there a friendly way to serialise/deserialise `Fn.getAtt("MyTopic", "TopicArn")` into yaml? Examples show use of:

```yaml
constructs:
  one-of-them-queues:
    type: queue
    worker:
      handler: worker.handler
    subscriptions:
      - topicRef:
          Fn::GetAtt:
            - MyTopic
            - TopicArn
```

for example, but what type am I expecting `topicRef` to be and/or how do I deserialise to an Fn so I can provide a serialised arn to `fromTopicArn` ?
