### DISCUSSION TITLE
How to specific the s3 bucket name of the static website?

### DISCUSSION THREAD

**Discussion by just-another-peter** [getlift/lift#362] [General]
As I have very limited access to the AWS resource, only able to create resources with specific naming rules.
That's why I must follow the naming rule of s3 bucket creation.

Either BucketPolicy and WebsiteBucket are not working. It is still creating a bucket name: **landingpageBucketXXXXX** 

Error:
CREATE_FAILED: landingpageBucket24A7B73E (AWS::S3::Bucket)
API: s3:CreateBucket Access Denied

Here is my serverless.yml
```yml
useDotenv: true

service: foobar

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage,'dev'}

  deploymentBucket:
    name: ${self:service}-${opt:stage,'dev'}-deploymentbucket

  environment:
    STAGE: ${opt:stage,'dev'}

plugins:
  - serverless-lift

constructs:
  landing-page:
    type: static-website
    path: ".output/public"

custom:
  lift:
    stages:
      - ${opt:stage,'dev'}
    bucketName: ${self:service}-${opt:stage,'dev'}-site

resources:
  Resources:
    # BucketPolicy:
    #   Type: AWS::S3::BucketPolicy
    #   Properties:
    #     Bucket: ${self:custom.lift.bucketName}

    # WebsiteBucket:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: ${self:custom.lift.bucketName}
```
