### DISCUSSION TITLE
How to add multiple email recipients in alarm option with queue construct

### DISCUSSION THREAD

**Discussion by garylparas** [getlift/lift#373] [Constructs]
Does the alarm option allow multiple email recipients?
```
constructs:
    my-queue:
        # ...
        alarm: alerting@mycompany.com
```
