### DISCUSSION TITLE
How to disable some construct based on stage, like disable for goerli and enable for mainnet. ServerlessIfElse is not able to exclude these constructs.

### DISCUSSION THREAD

**Discussion by vijaywankhede52243** [getlift/lift#375] [Constructs]
```
Example: 
constructs:
  indexIncomeQueue: 
    type: queue
    alarm: himanshu@blockswap.xyz
    maxRetries: 5
    batchSize: 10
    maxBatchingWindow: 10
    condition: ${self:custom.currentStage} == 'mainnet'
    worker:
      handler: src.index_epoch_apr_handler.data_handler
      timeout: 300
```

If I want to disable this construct only for goerli and I dont want to create diefferent serverless.yaml, how to do this ?
