### DISCUSSION TITLE
How to add multiple workers subscribe to the same single queue?

### DISCUSSION THREAD

**Discussion by Jeff-Tian** [getlift/lift#378] [General]
Is it possible to have multiple worker lambdas listen to the same queue? Something like:

```
constructs:
  jobs:
    type: queue
    workers:
      worker:
        handler: handler.consumer1
        ...
      worker:
        handler: handler.consumer2
        ...
```
