### DISCUSSION TITLE
[RFC] DynamoDB table

### DISCUSSION THREAD

**Discussion by mnapoli** [getlift/lift#54] [Constructs]
The goal of this discussion is to get feedback on a "DynamoDB table" construct.

## Use case

Setting up DynamoDB tables in serverless applications.

## Quick start

```yaml
# serverless.yml
# [...]

constructs:
    db:
        type: dynamodb
        partitionKey:
            name: id
            type: string
```

## How it works

On `serverless deploy`, the `dynamodb` construct will create a DynamoDB table preconfigured for production.

The table will be configured to [scale on-demand](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html#HowItWorks.OnDemand) (not provisioned). Costs will start at $0/month and will be proportional to the usage of the table.

[Point in time recovery](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html) will be enabled to get continuous backups for 35 days.

## Variables

All `dynamodb` constructs expose the following variables:

- tableName: the name of the DynamoDB table
- tableArn: the ARN of the DynamoDB table

These can be used to reference the queue from Lambda functions, for example:

```yaml
constructs:
    db:
        type: dynamodb
        # ...

functions:
    my-function:
        handler: function.handler
        environment:
            TABLE_NAME: ${construct:db.tableName}
```

How it works: the `${construct:db.tableName}` variable will automatically be replaced with a CloudFormation reference to the DynamoDB table.

## Permissions

By default, all the Lambda functions deployed in the same `serverless.yml` file will be allowed full access to the DynamoDB table.

### Primary key

DynamoDB primary keys are either:

- partition key
- partition key + sort key (composite key)

When only using a partition key:

```yaml
constructs:
    db:
        type: dynamodb
        partitionKey:
            name: id
            # The attribute type can be "string" (or "S"), "number" (or "N"), "binary" (or "B")
            type: string
```

When using a partition key + a sort key:

```yaml
constructs:
    db:
        type: dynamodb
        partitionKey:
            name: projectId
            type: string
        sortKey:
            name: userId
            type: string
```

---

Would a construct like this help in your projects? What would be missing?

**Comment by t-richard** [comment]
Seems to be a regular use case for serverless applications.

On-demand seems a good default and I don't see a need for it to be configurable in a first version.

Point in time recovery is also a nice thing to have by default. But I think it makes sense to make it configurable because PITR is not included in the always free tier of dynamodb and and isn't necessary if you are using dynamodb as a cache store.

**Reply by mnapoli** [reply]
Ah good point, cache usage is a different use case to keep in mind.

Either "cache" is too different from "database" as a use case (in terms of options/default settings) and we need a separate construct, either we can use one for both. If it's just a matter of disabling PITR then that could be an option indeed.

**Comment by fredericbarthelet** [comment]
Thanks for putting together this proposal @mnapoli :)

The equivalent CloudFormation configuration of your proposed API is (excluding point in time recovery):

```yml
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDB: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "projectId"
          AttributeType: "S"
        - 
          AttributeName: "userId"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "projectId"
          KeyType: "HASH"
        - 
          AttributeName: "userId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
```

I fill like there is not much addition provided by Lift on top of using straight CloudFormation.

Here are a few additional recommendations I'd stick by to ensure users can easily bootstrap a one-table configuration with minimal DynamoDB knowledges upfront:

- naming primary key column with non-generic names is a one-table design code smell, I would not offer the possibility to actually name them and rather stick with `PK` and `SK` with string type.
- LSI does not incur additional cost when no filled with data, however, adding those indexes at a later stage of development of the application requires it to be re-created. I'd include by default the maximum number of 5 LSI from the ground up with generic names `LSI1`, `LSI2`, ... By default, I'd use the projection ALL type to project all attributes and the string type for those attributes.
- I'd add a GSIQuantity property, by default equal to 0, provisioning the corresponding number of GSI, following a `GSI1_PK`/ `GSI1_SK` couple pattern as they are added/removed
- I would enable by default `TimeToLiveSpecification` and `StreamSpecification` as they don't affect pricing and are therefore available when required

Using single-table design prevents user from actually leveraging this construct when:
- not knowing in advance data access patterns
- using GraphQL with AppSync

However, I feel like those use-cases only represents a small part of DynamoDB users. WDYT ?
