### DISCUSSION TITLE
Append another CloudFront Function to the created Distribution in static-website construct

### DISCUSSION THREAD

**Discussion by InvisibleKind** [getlift/lift#78] [Constructs]
Hello again,

I'm making forward my journey to the serverless world :D

One of my next goals is to add Basic Auth to Cloudfront distributions, created in DEV and STAGE environments, and Cloudfront Functions is the perfect place for this functionality.

So I've added it under the resources:
```
resources:
  Resources:
    basicAuth:
      Type: AWS::CloudFront::Function
      Properties:
        AutoPublish: true
        FunctionCode: "function handler(event) {
    var request = event.request;
    var headers = request.headers;
    var authUser = 'xxx';
    var authPass = 'yyy;
    var authString = 'Basic ' + (authUser + ':' + authPass).toString('base64');
    if (typeof headers.authorization == 'undefined' || headers.authorization.value != authString) {
        var response = {
            statusCode: 401,
            statusDescription: 'Unauthorized',
            headers: {
                'www-authenticate': {value:'Basic'}
            },
        };
        return response;
    }
    return request;
};"
        FunctionConfig:
          Comment: 'serverless Basic Auth protection to prevent non-athorised access to dev and stage instances'
          Runtime: cloudfront-js-1.0
        Name: ${self:service}-${self:custom.stage}-basic-auth
```

The function is created, but I can't figure out, how can I attach it to the Cloudfront Distribution, created by lift. I assume I should do it in `resources.extensions` section and/or reference somehow with `!GetAtt`, but have no idea how.

Is there a way to achieve what I need?

**Comment by InvisibleKind** [comment]
Also a bonus question: can I pass user and pass per env variables or per Secrets somehow instead of hardcoding them in the function?

**Reply by fredericbarthelet** [reply]
Unfortunately, CloudFront functions needs to be synchronous, and therefore cannot rely on third party services (like the Parameter Store from SSM or Secret Manager) to handle secret management. AFAIK you also can set environnement variables for CloudFront functions.

**Reply by mnapoli** [reply]
> AFAIK you also can set environnement variables for CloudFront functions.

Don't you mean "you also _can't_ set environment variables"? Because I don't think you can.

**Reply by InvisibleKind** [reply]
Thank you for your answers. That's a pity, that the Secrets Manager and env vars can't be used in Cloudfront Functions in runtime, however I've found a way to extract login and password to env variables in a build time. I've used CloudFormation parameters for that.

As a result the login and password are not hardcoded and are not stored in git, which was important for me. 
They are still visible in CloudFormation template and in a function itself, but it is already better than before, because not exposed to every developer, but only to those, who have access to AWS Prod account and CI/CD system.

To make it work I've added following section to _provider_:
```
stackParameters:
    - ParameterKey: CloudFrontUsername
      ParameterValue: ${env:AWS_CF_USERNAME, self:custom.cloudfront.defaultUsername}
    - ParameterKey: CloudFrontPassword
      ParameterValue: ${env:AWS_CF_PASSWORD, self:custom.cloudfront.defaultPassword}
```

This to _resources_:
```
Parameters:
    CloudFrontUsername:
      Description: 'Basic Auth username in Cloudfront'
      Type: String
    CloudFrontPassword:
      Description: 'Basic Auth password in Cloudfront'
      Type: String
      NoEcho: true
```

_FunctionCode_ changed to this:
```
FunctionCode: !Sub "function handler(event) {
    var request = event.request;
    var headers = request.headers;
    var authUser = '${CloudFrontUsername}';
    var authPass = '${CloudFrontPassword}';
    var authString = 'Basic ' + (authUser + ':' + authPass).toString('base64');
    if (typeof headers.authorization == 'undefined' || headers.authorization.value != authString) {
        var response = {
            statusCode: 401,
            statusDescription: 'Unauthorized',
            headers: {
                'www-authenticate': {value:'Basic'}
            },
        };
        return response;
    }
    return request;
};"
```

And extended my _custom_ section:
```
cloudfront:
    defaultUsername: username
    defaultPassword: pass1234!
```
