### DISCUSSION TITLE
Declaring functions outside of `functions`

### DISCUSSION THREAD

**Discussion by mnapoli** [getlift/lift#8] [General]
I'll be using this discussion to track what we've learned about declaring Lambda functions outside of the `functions` section in serverless.yml.

For example with a "queues" component, the goal is to define the "worker" function inside the queue:

```yaml
service: app

provider:
  name: aws

queues:
  emails:
    worker:
      # This is a Lambda function
      handler: worker.handler
      # use any function property
```

The idea is to "copy" the content of `queues.emails.worker` into `functions`. Then Serverless should process that function as usual.

So far I've identified the following flow when Serverless runs:

- `scripts/serverless.js`
- `Serverless.run()` (`lib/Serverless.js`)
- `Service.setFunctionNames()` (`lib/classes/Service.js`)
- `initialize` hook
- other hooks

`Service.setFunctionNames()` normalizes the `functions`. I've tried inserting functions after that (in the `initialize` hook) but my inserted functions were causing errors later (because they were not normalized).

That means that:

1. Either we add functions after, and we replicate the behavior of `setFunctionNames()`
  This is risky: we run the risk of missing some behavior, not normalizing correctly, etc.
2. Or we add functions to `functions` before that

Ideally we would aim for solution 2. That means we can't use the `initialize` hook.

With that in mind, I've tested inserting the functions when the component boots. Simplified example:

```ts
export class MyComponent {
    constructor(serverless: Serverless) {
        // ...
        this.appendFunctions();
    }

    appendFunctions(): void {
        const configuration = this.getConfiguration() ?? {};
        Object.entries(configuration).map(([name, queueConfiguration]) => {
            Object.assign(this.serverless.service.functions, {
                [`${name}Worker`]: queueConfiguration.worker,
            });
        });
    }

  // ...
}
```

And in unit tests this is working!

We'll probably need more testing on this, see if this really works, especially with events, variables, config validation, or any other processing Serverless might do.

To those reading: if you have other ideas, please share :)

**Comment by m-radzikowski** [comment]
Wouldn't it be simpler and safer to just reference the function from the component by name? Like this:

```yaml
service: app

provider:
  name: aws

functions:
  worker:
    handler: worker.handler

queues:
  emails:
    function: worker
```
