### ISSUE TITLE
Create ECS

### ISSUE THREAD

**Issue by piolet** [getlift/lift#105]
Hi all,

starting from the predicate that our image exists (from ECR or docker hub), can we imagine a constructor that would take as argument the name of the image and, optionally, the cpu, the ram and the number of occurrences (etc. ?) and that would return as output the associated public ip :

```
service: my-app

provider:
    name: aws

plugins:
    - serverless-lift

constructs:

    # Include Lift constructs here

    my-service:
        type: ecs
        image: 'gotenberg' # from Docker hub for example
```

we could also specify a security group to complete the whole
