### ISSUE TITLE
Queue construct not working as documented

### ISSUE THREAD

**Issue by ledburyb** [getlift/lift#113]
Trying to adapt the documentation example so I can manage queues on dev differently but still use lift to create the production queues:
```
constructs:
  update-segment-memberships-from-contact-changes:
    type: queue

custom:
  update-segment-memberships-sqs-queue-arn:
    dev: ${env:UPDATE_SEGMENT_MEMBERSHIPS_FROM_CONTACT_CHANGES_QUEUE_ARN}
    staging: ${construct:update-segment-memberships-from-contact-changes.queueArn}
    demo: ${construct:update-segment-memberships-from-contact-changes.queueArn}
    production: ${construct:update-segment-memberships-from-contact-changes.queueArn}

functions:
  update_segment_memberships_from_contact_changes:
    events:
      - sqs:
          arn: ${self:custom.update-segment-memberships-sqs-queue-arn.${sls:stage}}
          batchSize: 10
          maximumBatchingWindow: 60
```

but getting:

```
Invalid configuration in 'constructs.update-segment-memberships-from-contact-changes': no 'worker' defined. Queue constructs require a 'worker' function to be defined.```
