### ISSUE TITLE
Allow to custom name for SQS queue

### ISSUE THREAD

**Issue by mlind2** [getlift/lift#121]
Is it possible to define custom queueName for a SQS queue? If not, please make it configurable.

**Comment by pfrantz** [comment]
Also it would be good to have the queue name constructed for environment variable and the SLS command line paramets

**Comment by neovasili** [comment]
We have a service defined in serverless with multiple queues triggering different lambda functions under the same code context so is quite useful to have the ability to define the queue name, which at the same time is good for org wide naming standards.

We ended up using a local copy of lift making the required change to enable queue names using something like this:

```yaml
constructs:
  messages-1:
    type: queue
    encryption: 'kmsManaged'
    name: queue-with-messages-type-1-${sls:stage}
    worker:
      timeout: 30
      name: lambda-for-handling-messages-1-${sls:stage}
...

  messages-2:
    type: queue
    encryption: 'kmsManaged'
    name: queue-with-messages-type-2-${sls:stage}
    worker:
      timeout: 30
      name: lambda-for-handling-messages-2-${sls:stage}

...
```

Having said that, I can make a pull request for this if you want 😄
