### ISSUE TITLE
[ServerSideWebsite] Expose Bucket in Output

### ISSUE THREAD

**Issue by piolet** [getlift/lift#130]
Hi all,

Would it be possible to expose the S3 Bucket in the output of the ServerSideWebsite construct ?

Indeed, I need to adjust some behaviors of this bucket via the `resources` of the serverless.yml, but currently, I can only do it after a first deployment, by manually retrieving the id via the stack created :

```
resources:
  extensions:
    ${construct:website.bucket}:
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
```
instead of
```
resources:
  extensions:
    websiteAssets2A73BB69:
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
```

thanks for time
