### ISSUE TITLE
FIFO SQS Queues FifoThroughputLimit and exposing other configurations.

### ISSUE THREAD

**Issue by carvajalluis** [getlift/lift#137]
Let me start by saying  thank you for the awesome work you have done with this project, very much appreciated.

I definitely wanted to ask you   how would I enable higher throughput  with the fifo queues, I'm generating about 20000   messages   in a couple of seconds but then I see them  eternally going  one by one with my FIFO queue like in 1 day or more. I just went  and enabled  manually  in my queues  on the AWS console the high throughput slider  but  its not  something  that can hold for the long run

```yml
  ContentBasedDeduplication: Boolean
  DeduplicationScope: String
  DelaySeconds: Integer
  FifoQueue: Boolean
  FifoThroughputLimit: String
  KmsDataKeyReusePeriodSeconds: Integer
  KmsMasterKeyId: String
  MaximumMessageSize: Integer
  MessageRetentionPeriod: Integer
  QueueName: String
  ReceiveMessageWaitTimeSeconds: Integer
  RedriveAllowPolicy: Json
  RedrivePolicy: Json
```
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/high-throughput-fifo.html

Also, according to that documentation that will increase throughput significantly, is from my perspective that  disabling  the deduplication  scope will  increase also performance of the queue but I couldn't find any documentation that will confirm or deny my assumption. The reason for me using FIFO Queues is because  the load on other resources can't tolerate concurrency: 
```yml
 myconstruct:
    type: queue
    fifo: true
    worker:
      handler: handler.generator
      timeout: 120
      provisionedConcurrency: 1
    maxRetries: 3
```

> I was wondering if it makes sense to expose AWS Cloud Formation API  within the lift construct  to tweak the FIFO queues depending on the use case. Also if  there is a walkaround that don't require  me to eject from lift.

**Comment by mnapoli** [comment]
Hi, just to be sure I understand here: are you 100% sure your queue is processed slowly because of the default SQS FIFO behavior? Or could it be accelerated by using batch processing, or by making Lambda worker jobs processed faster?

If you enable high throughput manually do you see a clear difference? (I've never used it personally)

And another question: what do you think the YAML config would look like with that new option?

**Comment by carvajalluis** [comment]
Both.

 my process is slow, I have some performance improvements  in development that will cut time to them by a factor of 1000.

but there is only so much performance improvements I can do to the work  while my Queues are  stuck. I mean  I see  thousands of messages not  in flight  processing  1 every 30 -120 seconds or more.

When I enable high throughput  I don't see a significant improvement of any kind . That  might be  hidden under  the fact  my process is slow  right now. 

 if you could , according to the premise of the serverless-lift , deploy production-ready fifo queues,  that meaning they are also tuned to be  their best performance possible.


If you rather expose those features and configurations to the  available to the end user of sls-lift  that is also fine for me , it could look like : 

```yml
 myconstruct:
    type: queue
    fifo: true
    deduplicationScope: message-group
    contentBasedDeduplication: true/false
    fifoThroughputLimit: per-message-group
    worker:
      handler: handler.generator
      timeout: 120
      provisionedConcurrency: 1
    maxRetries: 3
```
