### ISSUE TITLE
SQS Deployment error, can only contains alphanumeric

### ISSUE THREAD

**Issue by francoisauclair911** [getlift/lift#139]
Hi

I have this in my serverless.yml

```
service: ..........

provider: .........

plugins:
  - ./vendor/bref/bref
  - serverless-lift

constructs:
  jobs:
    type: queue
    worker:
      handler: worker.php
      layers:
        - ${bref:layer.php-80}
```
When I try a `sls deploy` I get the following error 
```  An error occurred: jobsDlqD18CF374 - Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 1e1c6d57-bd83-53f9-bb16-374e50fb6378; Proxy: null).```

Any ideas?
