### ISSUE TITLE
[Server-side website] Expose Bucket in output

### ISSUE THREAD

**Issue by piolet** [getlift/lift#140]
Hi all,

I was wondering if it would be possible to expose the bucket in the output of this manufacturer?

My use case would be the following. In the assets, I expose a sitemap.xml. But this sitemap evolves in time, and I would like to be able to update it via another cron lambda. But as it is, I can't pass the bucket as environment variable to this cron task.

What do you think about it ?

**Comment by t-richard** [comment]
Exposing the bucket could be possible but you would face other problems in your case.

At deploy time, the bucket is emptied so your generated sitemap would be deleted.

This is somewhat close to what was asked in #102

**Comment by piolet** [comment]
this is not really a problem.
In my case, the cron task is executed every night.
And I don't deploy every day ;) so the sitemap could "survive" some time between each deployment

**Comment by t-richard** [comment]
The problem is that your sitemap will be unavailable between your deploy and the next time your scheduled task generates it.

Maybe that's ok in your case but it's an overall poor experience.

**Comment by piolet** [comment]
We could invoke lambda just after deployment ? to avoid this problem.

with ci/cd it's not really a problem, no ?

**Comment by mnapoli** [comment]
I think the point Thibault is trying to make is that this feature in Lift wouldn't make sense in itself without #102, because it would provide a poor solution for users (they would have to work around that just like what you suggest).

So it wouldn't feel right to expose a solution that doesn't really work well. #102 might be a more complete solution for these cases it seems.

**Comment by t-richard** [comment]
Yes, exactly

And maybe we need to step back and see the bigger picture here.

The use-case is to be able to serve generated files alongside static files which have a completely different lifecycle.

From a separation of concerns standpoint, I feel like they belong to different buckets entirely.

Maybe an alternative approach would be something like this

```yaml
constructs:
    generated:
        type: storage

    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
            '/sitemap.xml': 
                storage: ${construct:generated.bucketArn}
                path: sitemap.xml
```

This opens up for a lot more use cases like serving uploaded files from the same Cloudfront distribution.

No strong opinion here, I just feel it might be a better solution.

**Comment by mnapoli** [comment]
@t-richard interesting 🤔 

But then the `${construct:generated.bucketArn}` bucket needs to be configured correctly (permissions/etc.) to be served from cloudfront, and so that's another can of worms? (or maybe I'm exaggerating)

I wonder if #102 couldn't be solved in a simpler way:

```yaml
constructs:
    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
            '/robots.txt': public/robots.txt
```

-> how about we sync only the paths listed in the config?

After all, we want to clear any extra CSS/JS file (because of hashes, there may be a lot of them). But we could ignore anything that doesn't match the paths listed in the config, and clear everything covered by the paths explicitly listed.

WDYT?

**Comment by piolet** [comment]
guys, bravo!
I really like your 2 solutions.
I wouldn't have thought of it.

It's true that in terms of architecture, it's more sexy than "just" providing the name of the bucket in output

**Comment by piolet** [comment]
However, the second solution can be problematic in certain configurations

Imagine a files directory that contains different files and that I put this whole directory in my configuration. 

If, for some reason, I decide to put my sitemap in this directory, it could be a problem. 

After that, you can leave it to the user. If the documentation speaks about it, it can be enough to modify the output of the sitemap

**Comment by t-richard** [comment]
Yeah, it was just an example to emphasize on fusing on the use-case first, not sure how much feasible it is but that may be an idea worth digging into.

On your proposal, I see two things that could cause issues.

First, let's say I have this config 

```yaml
constructs:
    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
            '/robots.txt': public/robots.txt
```

Now I change it to this

```diff
constructs:
    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
-           '/robots.txt': public/robots.txt
```

The `robots.txt` will never get deleted from the bucket. It would be the same if I renamed a folder, from `images` to `pictures` for example.

Also, I have the feeling it could lead to problematic situations. In the case of the `storage` construct, running a `serverless remove` would fail the stack deletion because the bucket will not be emptied.

In the case of this construct, the bucket is considered disposable and is emptied automatically upon running `serverless remove`. 

This is why I tend to think we should make the "bad decisions" very hard to make. If storing a sitemap, it's not a big deal but if we are talking about business critical files, it can be a real issue.

And finally, this solution would not allow the file to be served by Cloudfront. Because `sitemap.xml` is not listed in the `assets` key, the constrcut would not create a behaviour for it, making it innaccessible to the outside world. It would be redirected to the API gateway instead.

Let me know your thoughts on this :slightly_smiling_face:
