### ISSUE TITLE
[server-side-website] Which certificate choose with multi domain configuration

### ISSUE THREAD

**Issue by piolet** [getlift/lift#146]
### Description

Hi all,

Deployment with multiple domains does not work the first time
I don't know if I'm missing something on my first deployment, but at second one, it's ok (with some modifications)

This the error :
```
Serverless Error ----------------------------------------
 
  An error occurred: websiteCDN060D946D - Resource handler returned message: "Invalid request provided: The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME) that you're trying to add. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements (Service: CloudFront, Status Code: 400, Request ID: ca14f3e0-d957-4bb4-91f3-2005c466a3c6, Extended Request ID: null)" (RequestToken: 06630fbf-8cb4-f097-b820-4d137e0aba54, HandlerErrorCode: InvalidRequest).

```
But with the same certificats, depending on the case, it's ok. I don't understand what i missed

### How to Reproduce

This my setup :
```
constructs:
  website:
    type: server-side-website
    domain:
      - ${self:custom.domain}
    # - !Sub "www.${self:custom.domain}" # 1
    # ARN of an ACM certificate for the domain, registered in us-east-1
    # specific certificate for main domain : example.com
    certificate: arn:aws:acm:us-east-1:xxx:certificate/8a0a205f-6931-4855-b3db-0370ea3fbc55 # 2
    # star certificate for domain : *.example.com
    # certificate: arn:aws:acm:us-east-1:xxx:certificate/adefc574-6886-4719-a922-e2e50b975acd # 3
    # redirectToMainDomain: true # 4
    assets: ...
```

this deployment does not work the first time.
I have to deploy a first time with only one domain (the first one).
Then, once this deployment is successful, I start again by commenting out the first certificate (# 2) and uncommenting the lines associated with this second domain (#1, #3, #4). And after it works

Do you have an idea ?

### Additional Information

I configure all my domain like this :
```
resources:
     MainRoute53Record:
            Type: AWS::Route53::RecordSet
            Properties:
                HostedZoneId: ZXXXXXXXXXXXXXXXXXXJ # Your HostedZoneId
                Name: ${self:custom.domain}
                Type: A
                AliasTarget:
                    HostedZoneId: Z2FDTNDATAQYW2 # Cloudfront Route53 HostedZoneId. This does not change.
                    DNSName: ${construct:website.cname}
     WwwRoute53Record:
            Type: AWS::Route53::RecordSet
            Properties:
                HostedZoneId: ZXXXXXXXXXXXXXXXXXXJ # Your HostedZoneId
                Name: !Sub "www.${self:custom.domain}"
                Type: A
                AliasTarget:
                    HostedZoneId: Z2FDTNDATAQYW2 # Cloudfront Route53 HostedZoneId. This does not change.
                    DNSName: ${construct:website.cname}
```

Maybe the second must be a CNAME ?

I will also complete with this.
When I use my certificate for *.example.com, of course the first domain (my main domain) example.com is no longer certified since it needs a certificate for example.com specifically as shown here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements

So, the multi-domain configuration is a problem when the domains are not at the same level
