### ISSUE TITLE
TypeError: Cannot read property 'defineTopLevelProperty' of undefined

### ISSUE THREAD

**Issue by onlinesid** [getlift/lift#148]
### Description

I keep getting this error when trying to deploy. I kept checking if I missed any step from the guide but could not see anything wrong.

```bash
$ export SLS_DEBUG=true; sls deploy -v
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'defineTopLevelProperty' of undefined
      at _LiftPlugin.registerConfigSchema (/home/user/Projects/my-bref-project/node_modules/serverless-lift/src/plugin.ts:160:45)
      at new _LiftPlugin (/home/user/Projects/my-bref-project/node_modules/serverless-lift/src/plugin.ts:133:14)
      at PluginManager.addPlugin (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:77:28)
      at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:114:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:114:8)
      at /usr/lib/node_modules/serverless/lib/Serverless.js:96:35
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Serverless.init (/usr/lib/node_modules/serverless/lib/Serverless.js:94:8)
      at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:79:4)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.3
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.11
 ```

### How to Reproduce

```yaml
service: my-bref-project

provider:
    name: aws
    region: ap-southeast-2
    runtime: provided.al2
    profile: myawsprofile
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        BREF_BINARY_RESPONSES: '1'
        GC_API_KEY: ${file(./variables.json):GC_API_KEY}
        TEST_ENV_VAR: ${file(./variables.json):TEST_ENV_VAR}
plugins:
  - ./vendor/bref/bref
  - serverless-lift
functions:
    index:
        handler: public/index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - httpApi:
                method: GET
                path: /
    play:
        handler: public/play.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - httpApi:
                method: GET
                path: /play
constructs:
  website:
    type: server-side-website
    apiGateway: 'http'
    assets:
        '/audio/*': assets/audio
        
# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
        - '!.serverless/**'
        - '!variables.json'
        - '!build.php'

```
