### ISSUE TITLE
[Storage] - how to add/modify lifecycle rule

### ISSUE THREAD

**Issue by piolet** [getlift/lift#149]
### Start from the Use-case

I want use a storage construct to store some database's backup.
these backups are created daily and I don't need to store them ad vitam.
Ideally, I would like to be able to store the last x backups and therefore delete the older ones (after x + 1 days)

maybe it's already possible to do this with another way, but which one ? ;)

thank for your reply

### Example Config

```
constructs:
    avatars:
        type: storage
        expiration_in_days: X
```
to add in fact this kind of rule :
```
LifecycleConfiguration:
        Rules:
          - Id: Rule to delete files
            Status: Enabled
            ExpirationInDays: X
```
