### ISSUE TITLE
Added ability to customize Policy Statements, specifically for Storage

### ISSUE THREAD

**Issue by JonErickson** [getlift/lift#153]
### Start from the Use-case

Current the default policy statement for s3 Storage is ["s3:PutObject", "s3:GetObject", "s3:DeleteObject", "s3:ListBucket"].
Because this is hardcoded, additional policies cannot be added. For example, s3:PutObjectAcl is needed quite often in many applications when you have ACL's enabled and you need to make an object public, that is private by default.

### Example Config

```
constructs:
  files:
    type: storage
    permissions:
      - s3:PutObject
      - s3:GetObject
      - s3:DeleteObject
      - s3:ListBucket
      - s3:PutObjectAcl
```

### Implementation Idea

Add ability to add extra permissions to/or overwrite the policy statement for Storage.
