### ISSUE TITLE
Trying to use other serverless tool commands causes issue with serverless-wsgi

### ISSUE THREAD

**Issue by babyhuey** [getlift/lift#154]
### Description

When I try to run a command from serverless-wsgi, it is throwing an error from lift. 

```
sls -s dev wsgi manage --command "migrate"
 
 Error ---------------------------------------------------
 
  Error: Constructs are already initialized: this should not happen
      at _LiftPlugin.loadConstructs (/code/mmasync-sqs-poc/node_modules/serverless-lift/dist/src/plugin.js:175:13)
      at initialize (/code/mmasync-sqs-poc/node_modules/serverless-lift/dist/src/plugin.js:92:14)
      at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:648:65)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.2
     Framework Version:         2.65.0
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1
```

### How to Reproduce

```
service: async-serverless

provider:
  name: aws
  runtime: python3.8
  vpc:
    securityGroupIds: ${file(config-${opt:stage}.yaml):securityGroups}
    subnetIds: ${file(config-${opt:stage}.yaml):subnets}
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-lift

constructs:
    jobs:
        type: queue
        worker:
            handler: mmasync.lambdas.async_task_handler
            environment:
              DJANGO_SETTINGS_MODULE: sqspoc.settings

custom:
  wsgi:
    app: sqspoc.wsgi.application
functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any
    environment:
      MMASYNC_SQS_QUEUE_NAME: ${construct:jobs.queueUrl}

```

### Additional Information

sls --version
Framework Core: 2.65.0
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1

+ serverless-python-requirements@5.3.0
+ serverless-lift@1.11.0
+ serverless-wsgi@3.0.0
+ serverless-prune-plugin@2.0.1
