### ISSUE TITLE
Support dynamic stage from env (serverless-dotenv-plugin)

### ISSUE THREAD

**Issue by jaredchu** [getlift/lift#156]
### Start from the Use-case

There is an error when deploying if stage configuration using environment variable.

Expected:
`serverless deploy` successfully

Actual:
Error happens
```
An error occurred: [workername] - The name of a FIFO queue can only include alphanumeric characters, hyphens, or underscores, must end with .fifo suffix and be 1 to 80 in length. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: [request-id]; Proxy: null).
```

### Example Config

serverless.yaml:
```
provider:
  stage: ${env:STAGE}
constructs:
  jobs:
    type: queue
    fifo: true
    worker:
      handler: jobs.handler
```

### Implementation Idea

Please support `serverless-dotenv-plugin` functioning
