### ISSUE TITLE
Allow customizing event bus name for a webhook

### ISSUE THREAD

**Issue by moein** [getlift/lift#167]
### Start from the Use-case

When trying to deploy 2 different stages of an application into the same AWS account the deploy fails for the second stage since the same bus name is generated for the webhook.

### Example Config

```yml
constructs:
  myWebhook:
    type: webhook
    name: ${self:provider.stage}-myWebhook
    eventType: $request.header.event
    path: /webhook
```

### Implementation Idea

Currently, the key is used for generating the bus name and we can not use variables in the keys to add stage in the name.
Allowing passing a field like busName or bus.name for webhook construct can solve the issue.
As of right now I have put constructs under custom and using a js file I'm adding the stage to the keys of webhook constructs.
If you give me a hint how the key is passed as the name of the webhook event bus I would be happy to contribute.
