### ISSUE TITLE
Add optional reportBatchItemFailures setting

### ISSUE THREAD

**Issue by agoodno** [getlift/lift#173]
### Start from the Use-case

When the event source mapping is created using the Lift plugin, the [functionResponseType attribute is set to "ReportBatchItemFailures"](https://github.com/getlift/lift/blob/master/src/constructs/aws/Queue.ts#L253). For whatever reason, this causes every message sent from this trigger to fail in my Lambda function and not be processed. Manually re-creating the event source without this feature allows the message to be consumed normally by my Lambda function.

### Example Config

```
constructs:
  my-queue:
    type: queue
...
    reportBatchItemFailures: false
    worker:
      handler: handler.handler
...
```

### Implementation Idea

My suggestion is to allow this attribute to be added by default as it currently is, but allow a setting `reportBatchItemFailures` to be passed to the plugin which allows it to be turned off. My work-around is to fork this repo and remove that setting.
