### ISSUE TITLE
Defining SQS Consumer away from construct

### ISSUE THREAD

**Issue by AndrewCEmil** [getlift/lift#185]
Is it possible to define an SQS consumer function away from the construct definition?

I would like to do something like:

```
functions:
  myFunction:
    ...
    events:
      - sqs:
        arn: ${construct.myQueue.queueArn}

constructs:
  myQueue:
    type: queue
```

This will allow me to keep my function definitions together, which is especially nice for lambda functions that have multiple event types. This is especially important for making functions that take both an SQS and S3 events as input.

Right now, it seems like the queue type requires a worker definition, making a configuration like this impossible. Is that correct? (See code here: https://github.com/getlift/lift/blob/master/src/constructs/aws/Queue.ts#L133-L135. BTW This error is swallowed for me, the output I get is a generic `Configuration error at 'constructs.perfTestErrors': unsupported value`)

But perhaps I am just doing this wrong. Any thoughts?

PS: I would have opened this as a "Discussion", but github won't let me - that might be a permissions thing?
