### ISSUE TITLE
Implement resources extensions to allow further customization of Lift Constructs underlying CFN resources

### ISSUE THREAD

**Issue by fredericbarthelet** [getlift/lift#191]
### Use-case

They are a lot of issue regarding the addition of a new property on existing Lift constructs to hydrate a specific underlying CFN property. All issues are tagged with `custom property` label. This issue aims at finding a better way to extend constructs.

Current recommendation to do just that leverages [`resources.extensions` property](https://www.serverless.com/framework/docs/providers/aws/guide/resources/#override-aws-cloudformation-resource) to override specific properties. However, this method has the disadvantage to rely on LogicalIDs generated by the CDK in Lift:

```yml
# serverless.yml
service: my-app
provider:
    name: aws

constructs:
    landing:
        type: static-website
        path: public

plugins:
    - serverless-lift 
    
resources:
    extensions:
        LandingBucketF057328A:
            Properties:
                ObjectLockEnabled: true
```

This issue aims at finding a way not to have to version LogicalIDs of resources generated by Lift.

### Implementations proposals

There are multiple possible ways to declare extensions

**Using a global `lift.extensions` property**
```yml
# serverless.yml
service: my-app
provider:
    name: aws

constructs:
    landing:
        type: static-website
        path: public

plugins:
    - serverless-lift 
    
lift:
    extensions:
        landing.bucket:
            Properties:
                ObjectLockEnabled: true
```

At deployment time, Lift will replace `landing.bucket` with the S3 bucket LogicalId generated by Lift for the Static Website construct

**Using a construct scoped `extensions` property**
```yml
# serverless.yml
service: my-app
provider:
    name: aws

constructs:
    landing:
        type: static-website
        path: public
        extensions:
            bucket:
                Properties:
                    ObjectLockEnabled: true

plugins:
    - serverless-lift 
```

For both exemples, each construct will expose a set of resources corresponding to final CFN resources created.
For exemple, in the storage construct, `bucket` property will reference underlying `[AWS::S3::Bucket](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) resource`
