### ISSUE TITLE
How to implement multiple queue

### ISSUE THREAD

**Issue by ridozito** [getlift/lift#207]
### Description

I want to implement multiple queue but when I try below , deploy has occurs error

### How to Reproduce

```
constructs:
  queue1:
    type: queue
    worker:
      handler: handler.job1

  queue2:
    type: queue
    fifo: true
    worker:
      handler: hander.job2
```
