### ISSUE TITLE
Storage extensions: malformed arrays

### ISSUE THREAD

**Issue by kevincerro** [getlift/lift#219]
### Description

If you create a storage construct that uses yaml lists inside extensions, the output produces malformed arrays in 
CloudFormation template.

Expected output:
```
"CorsConfiguration": {
  "CorsRules": [
    {
      "AllowedOrigins": [
        "*"
      ],
      "AllowedHeaders": [
        "*"
      ],
      "AllowedMethods": [
        "GET",
        "HEAD",
        "PUT",
        "POST"
      ]
    }
  ]
}
```

Current output:
```
"CorsConfiguration": {
  "CorsRules": {
    "0": {
      "AllowedOrigins": {
        "0": "*"
      },
      "AllowedHeaders": {
        "0": "*"
      },
      "AllowedMethods": {
        "0": "GET",
        "1": "HEAD",
        "2": "PUT",
        "3": "POST"
      }
    }
  }
},
```
<img width="458" alt="Captura de Pantalla 2022-06-01 a las 19 16 27" src="https://user-images.githubusercontent.com/13980708/171464155-384b5f12-3778-4174-9f17-9fb045da4ef0.png">

### How to Reproduce

Create one storage construct like this and try to deploy.

```
constructs:
    uploads:
        type: storage
        extensions:
            bucket:
                Properties:
                    CorsConfiguration:
                        CorsRules:
                            - AllowedOrigins:
                                  - '*'
                              AllowedHeaders:
                                  - '*'
                              AllowedMethods:
                                  - GET
                                  - HEAD
                                  - PUT
                                  - POST
```
