### ISSUE TITLE
Installing Lift and configuring a queue causes node_modules to get uploaded and hit lambda limit

### ISSUE THREAD

**Issue by seantcanavan** [getlift/lift#231]
### Description

I had an existing GoLang AWS Serverless project working perfectly that I wanted to add an SQS queue to. I saw that `lift` could achieve this rather easily so I was excited to try it out.

I followed the guide at `https://github.com/getlift/lift/blob/master/docs/queue.md` and as soon as I did `serverless deploy` my upload bundle went from 25MB to 126MB. I'm 90% sure that this is because it's now bundling the `node_modules` folder that `serverless plugin install -n serverless-lift` creates.

I tried adding `exclude` keywords to not upload this folder without luck. Any ideas on how to proceed would be awesome.

### How to Reproduce

```
org: org
app: app
service: service

configValidationMode: error

frameworkVersion: ">=2.24.0"

provider:
  name: aws
  runtime: go1.x
  environment:
    APP_NAME: ${param:APP_NAME}
    CONNECTION_STRING: ${param:CONNECTION_STRING}
    CORS_METHODS: ${param:CORS_METHODS}
    CORS_ORIGIN: ${param:CORS_ORIGIN}
    HMAC_SECRET: ${param:HMAC_SECRET}
    STAGE: ${param:STAGE}

functions:
  api:
    handler: bin/main
    package:
      exclude:
        - node_modules/**
      patterns:
        - './bin/main'
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

constructs:
  async:
    type: queue
    fifo: true
    worker:
      handler: bin/sqs
      package:
        exclude:
          - node_modules/**
        patterns:
          - './bin/sqs'

plugins:
  - serverless-lift
```

### Additional Information

Environment: linux, node 16.15.0, framework 3.19.0 (local) 3.19.0v (global), plugin 6.2.2, SDK 4.3.2

Error:
UPDATE_FAILED: ApiLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: f379506a-662b-4d23-a74a-eb64db66b841)" (RequestToken: ff10e5b6-3f8e-20e3-70f3-5838f6d7701d, HandlerErrorCode: InvalidRequest)

EDIT: This appears to be an issue at first glace on the `serverless` side. I'm having an incredibly difficult time to get the `serverless package` command to respect any kind of filter includes, excludes or glob patterns whatsoever. This means every time I deploy it's getting every file in the folder and uploading it via the zip which breaks the upload limit. For now i'm playing around with `package: individually: true` and `package: artifact: main.zip` to cut out all of the unnecessary files. This just worked for me so I'm going to try using lift again to see if I can get it to work.

**Comment by seantcanavan** [comment]
So for reasons I have no idea why no configuration of `patterns`, `include`, or `exclude` could get `serverless` to correctly package my golang project into two distinct packages. It just threw every file, or no files at all, into each zip. In the case that nothing was packaged, the lambda crashed. In the case that everything was packaged, `lift` caused the packaged bundle to be too large. I'll share my `serverless.yml` below in hopes that it helps someone else build a project with `serverless`, `lift`, `golang`, AWS Lambda, and AWS SQS.


```
org: serverless-org
app: serverless-app
service: serverless-service

configValidationMode: error
frameworkVersion: ">=2.24.0"
package:
  individually: true

provider:
  name: aws
  runtime: go1.x
  environment:
    APP_NAME: ${param:APP_NAME}
    AWS_ACCESS_KEY_ID: ${param.AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${param.AWS_SECRET_ACCESS_KEY}
    CONNECTION_STRING: ${param:CONNECTION_STRING}
    CORS_METHODS: ${param:CORS_METHODS}
    CORS_ORIGIN: ${param:CORS_ORIGIN}
    HMAC_SECRET: ${param:HMAC_SECRET}
    STAGE: ${param:STAGE}

functions:
  api:
    handler: bin/main
    package:
      artifact: bin/main.zip
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true

constructs:
  async:
    type: queue
    fifo: true
    worker:
      handler: bin/sqs
      package:
        artifact: bin/sqs.zip
      events:
        - sqs:
            arn:
              Fn::Join:
                - ':'
                - - arn
                  - aws
                  - sqs
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - async-${self:service}-${sls:stage}

plugins:
  - serverless-lift
```

And the `make` commands which individually build both the HTTP Rest API Lambda Handler and the SQS API Lambda Handler and create the .zips that `serverless` then deploys with the above code:

```
build:
	env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/main main.go
	env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/sqs sqs.go
	zip bin/main.zip bin/main
	zip bin/sqs.zip bin/sqs

clean:
	rm -rfv ./bin

deploy-all: deploy-staging deploy-production

deploy-staging: pre-deploy
	serverless deploy --verbose --stage staging --region us-east-2 --org serverless-org

deploy-production: pre-deploy
	serverless deploy --verbose  --stage production --region us-east-2 --org serverless-org
```
