### ISSUE TITLE
Allow changing the CloudFront Function name

### ISSUE THREAD

**Issue by felipe-dsdev** [getlift/lift#242]
### Start from the Use-case

The name of my serverless service added to the stage is longer than 38 characters and with the additional 26 characters placed by the lift (region and text "website-request"), it exceeds the 64 character limit for the CloudFront Function name.

### Example Config

```yml
constructs:
  website:
    name: ServiceNameDefinedByConfiguration
    type: server-side-website
```
