### ISSUE TITLE
Since 1.20.1: Cannot deploy multiple stages of a server-side-website to the same AWS account

### ISSUE THREAD

**Issue by amacrobert-meq** [getlift/lift#247]
### Description

Version 1.20.1 has the change "Remove manual construction of cloudfront function name to avoid max length constraint by @fredericbarthelet #245 ".

That manual construction of the cloudfront function name apparently was what prevented resource collisions.

Now, deploying the same service to 2 different `stage`s in the same AWS account causes a naming collision, preventing the 2nd deployment from completing:

```
× Stack workforce-campaigns-stage2 failed to deploy (286s)
Environment: linux, node 16.15.1, framework 3.21.0 (local) 3.14.0v (global), plugin 6.2.2, SDK 4.3.2
...

Error:
CREATE_FAILED: websiteRequestFunction9E9EBB7A (AWS::CloudFront::Function)
Resource handler returned message: "Resource of type 'AWS::CloudFront::Function' with identifier 'us-east-1websiteRequestFunction1129A88C' already exists." (RequestToken: 1426a5a9-e4ab-bf7c-ea0c-2431645d7f85, HandlerErrorCode: AlreadyExists)
```

### How to Reproduce

1. Create a server-side-website construct including the following :
    ```
    constructs:
        website:
            type: server-side-website
            assets:
                '/dist/*': public/dist
            forwardedHeaders:
                - Accept
                - Accept-Language
                - Authorization
                - Content-Type
                - Origin
                - Referer
                - User-Agent
                - X-Forwarded-Host
                - X-Requested-With
    ```

2. Deploy that to any given stage. It will succeed. `sls deploy --stage test1`
3. Deploy that to a different stage. It will fail. `sls deploy --stage test2`

### Additional Information

Separately (and this is a smaller issue), 1.20.1 is backwards-incompatible with 1.20.0. You cannot update a server-side-website that was built using serverless-lift <= 1.20.0 with 1.20.1. I suggest that a fix to the above bug is released as 1.21.0 (or 2.0.0), and 1.20.1 is deleted because users probably expect a maintenance version not to break compatibility.
