### ISSUE TITLE
Add ability to auto-detect ACM certificates by best-match

### ISSUE THREAD

**Issue by BenCoffeed** [getlift/lift#255]
### Start from the Use-case

I would like to use lift to expand my existing backend repository running on Serverless/Bref to include my frontend webpack SPA as well. Currently, I use a combination of shell scripts and serverless plugins to make this happen. However, I would like to be able to utilize Lift to reduce my dependence on pre-existing cloudfront distributions, route53 records, and ACM certificates. This would decrease the footprint of infrastructure not currently covered by code significantly and pull more of that into a single solution, the serverless framework. I use the [serverless-certificate-creator plugin](https://www.serverless.com/plugins/serverless-certificate-creator) to create custom ACM certificates. However, when referencing the output of the plugin in the construct for my frontend application, I recieve the following error: 

`Invalid configuration for the static website 'frontend': if a domain is configured, then a certificate ARN must be configured in the 'certificate' option.
See https://github.com/getlift/lift/blob/master/docs/static-website.md#custom-domain`

```yaml
service: myService
plugins:
  - serverless-certificate-creator
  - serverless-lift

constructs:
  landing:
    type: single-page-app
    path: ${param:frontendDist}
    domain: ${param:domainName}
    certificate: ${certificate(${self:custom.customCertificate.certificateName}):CertificateArn}

params:
  default:
    domainName: ${self:service}.${sls:stage}.acme.com
    frontendDist: vendor/myService-frontend-Repo/myService-frontend/dist
  dev:
    frontendDist: ${env:FRONT_END_DIST, "vendor/roundingwell/care-ops-frontend/dist"}

custom:
  customCertificate:
    certificateName: ${param:domainName}
    hostedZoneNames: ${param:domainName}
    subjectAlternatives:
      - '*.${param:domainName}'
```

I think a very simple workaraound for this would be copying the style of the [serverless-domain-manager plugin](https://www.serverless.com/plugins/serverless-domain-manager) certificateName parameter which attempts to make a best effort assumption about which certificate to use based on the domain name based on the closest match by default.

> The name of a specific certificate from Certificate Manager to use with this API. If not specified, the closest match will be used (i.e. for a given domain name api.example.com, a certificate for api.example.com will take precedence over a *.example.com certificate).Note: Edge-optimized endpoints require that the certificate be located in us-east-1 to be used with the CloudFront distribution.

### Example Config

```yaml
landing:
    type: single-page-app
    path: ${param:frontendDist}
    domain: ${param:domainName}

### Implementation Idea

This is copied directly from the [serverless-domain-manager plugin source](https://github.com/amplify-education/serverless-domain-manager/blob/58f5d363972697d9e5264f698966cbd06776f091/src/aws/acm-wrapper.ts)

```typescript
 private async getCertArnByCertName(certificates, certName): Promise<string> {
        // note: we only check DomainName, but a future enhancement could
        // be to also check SubjectAlternativeNames
        const matches = certificates.filter((certificate) => (certificate.DomainName === certName));
        for (const certificate of matches) {
            const certificateArn = certificate.CertificateArn;
            const details = await throttledCall(
                this.acm,
                "describeCertificate",
                {CertificateArn: certificateArn},
            );
            const currNotAfter = details.Certificate.NotAfter;
            if (Date.now() < currNotAfter) {
                Globals.logInfo(
                    `Selecting cert with ARN=${certificateArn} with future expiry (${currNotAfter.toISOString()})`
                );
                return certificateArn;
            }
            Globals.logInfo(
                `Ignoring cert with ARN=${certificateArn} that is expired (${currNotAfter.toISOString()})`
            );
        }
    }
```
