### ISSUE TITLE
Add Ability to Add custom behavior

### ISSUE THREAD

**Issue by BenCoffeed** [getlift/lift#256]
### Start from the Use-case

I would like to be able to incorporate Lift into my existing pipeline by fully automating my CloudFront distributions. This includes the ability to add custom behaviors for my `/api` path which I would like to forward to an API gateway-hosted function. The simplest way to do this is to create a custom domain for my api gateway distribution that matches exactly my app URL without creating a DNS entry for it. For example: `myservice.acme.com`.  By adding the custom domain without a DNS entry, I have added my domain to the allowed values of the `origin` header for requests hitting the API gateway endpoint. This means I can have a behavior on my cloudfront distribution that remaps all requests to the `/api*` path pattern to the api gateway internal default invoke URL such as `https://${someRandomId}.execute-api.us-west-2.amazonaws.com/`. Since the A record for `myservice.acme.com` is pointing to my distribution, the origin header allows the distribution to make the call this way. You can also accomplish this with some lambda@edge header rewriting, but it's not necessary for this simple setup.

### Example Config

```yaml
service: myService

constructs:
    landing:
      type: single-page-app
      path: ${param:frontendDist}
      domain: ${param:domainName}z
      apiPathPattern: api*
      apiGatewayUrl: !Ref HttpApiUrl 
      certificate: ${certificate(${self:custom.customCertificate.certificateName}):CertificateArn}
      
functions:
  api:
    name: ${self:service}-api
    handler: api.php
    timeout: 28
    layers:
      - ${bref:layer.php-81-fpm}
    description: 'Care Team Ops HTTP API'
    reservedConcurrency: ${param:reservedConcurrencyApi}
    events:
      - httpApi: '*'
    tags:
      service: api
```

### Implementation Idea

Add an additional behavior with path pattern, forwarding all headers, etc to the provided invoke URL.

**Comment by mnapoli** [comment]
Hi, this looks similar to #82, is there a difference?

**Comment by BenCoffeed** [comment]
I think the use-case is similar, but I think my idea for implementation is somewhat more generic, though now that I review my "example config", I believe I drifted from my generic ideal. Originally, I was perusing to see if there was an output of the CloudFront distribution created by Lift that I could reference to add a custom behavior resource. However, if I'm reading the AWS CloudFormation documentation correctly, the membership of CacheBehavior objects occurs within the distribution object and there does not appear to be a way to associate a CacheBehavior object after the fact. I believe a better example configuration idea would be 

```yaml
service: myService

constructs:
    landing:
      type: single-page-app
      path: ${param:frontendDist}
      domain: ${param:domainName}
      certificate: ${certificate(${self:custom.customCertificate.certificateName}):CertificateArn}
      behaviors:
         -  origin: 
              type: Custom
              target: !Ref HttpApiUrl
              OriginProtocolPolicy: https-only
            AllowedMethods: 
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - DELETE
            CachedMethods: 
              - GET
              - HEAD
              - OPTIONS
            CachePolicyId: abcd456a-a123-4567-89abc-defgh01234abc
            Compress: False
            DefaultTTL: 30
            FunctionAssociations: 
              - arn:aws:cloudfront:::function/MyFunction
            LambdaFunctionAssociations: 
              - arn:aws:lambda:us-east-1::function:myFunction:2
            OriginRequestPolicyId: abcd456a-a123-4567-89abc-defgh01234abc
            PathPattern: api*
            ViewerProtocolPolicy: https-only
      
      
functions:
  api:
    name: ${self:service}-api
    handler: api.php
    timeout: 28
    layers:
      - ${bref:layer.php-81-fpm}
    description: 'Care Team Ops HTTP API'
    reservedConcurrency: ${param:reservedConcurrencyApi}
    events:
      - httpApi: '*'
    tags:
      service: api
```
The implementation would be to simply create a CloudFormation CacheBehavior object definition for the listed behaviors and include them in the distribution. The `origin` object could first test if origin already existed before attempting to create simply based on `target`. Additionally, I left most of the default CloudFormation parameter names here just as a quick reference, but I suspect many could be removed and/or renamed to simplify/standardize the config.
