### ISSUE TITLE
Alarm extension not working properly on queues

### ISSUE THREAD

**Issue by codentacos** [getlift/lift#265]
### Description

I am attempting to create a CloudWatch alarm for a dead letter queue and it seems like this is not functioning as expected and may be a bug. Below is an example snippet of my queue construct. The idea here is to create a CloudWatch alarm that is only enabled in specific environments and the value is retrieved from `serverless.env.yml`

```
constructs:
  shipmentsUpdateQueue:
    type: queue
    fifo: true
    worker:
      handler: src/sqsHandlers/shipmentUpdateHandler.handle
    alarm: someemail@test.com
    extensions:
      alarm:
        Properties:
          ActionsEnabled:  ${self:custom.config.enableDeadLetterQueueAlarmActions}
```

Below is a snippet from the output CloudFormation template in the `.serverless` directory. The `ActionsEnabled` property is being set on the queue instead of the alarm as expected.
```
...
"shipmentsUpdateQueueDlqDF8B0233": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "FifoQueue": true,
        "MessageRetentionPeriod": 1209600,
        "QueueName": "shipments-pr-8-shipmentsUpdateQueue-dlq.fifo",
        "ActionsEnabled": false,
...
```

I am also receiving the following error when I attempt to deploy to a PR stack
```
Error:
UPDATE_FAILED: shipmentsUpdateQueueDlqDF8B0233 (AWS::SQS::Queue)
Properties validation failed for resource shipmentsUpdateQueueDlqDF8B0233 with message:
#: extraneous key [ActionsEnabled] is not permitted
```

### How to Reproduce

This is my related serverless constructs configuration

```
constructs:
  shipmentsUpdateQueue:
    type: queue
    fifo: true
    worker:
      handler: src/sqsHandlers/shipmentUpdateHandler.handle
    alarm: someemail@test.com
    extensions:
      alarm:
        Properties:
          ActionsEnabled:  ${self:custom.config.enableDeadLetterQueueAlarmActions}
```
