### ISSUE TITLE
Add SNS subscriptions to queues

### ISSUE THREAD

**Issue by jesusch** [getlift/lift#266]
I assum this could be a common usecase

```
constructs:
  my-queue:
    type: queue
    subscriptions:
    - arn:aws:sns:us-east-1:1234567890:my-topic
    - arn:aws:sns:eu-west-1:1234567890:my-othertopic
```

**Comment by mnapoli** [comment]
What would be the use case?

**Comment by jesusch** [comment]
Subscribe sqs queues to sns topics

**Comment by ryanwalters** [comment]
> What would be the use case?

A common pattern, usually called "fanout", is to subscribe SQS queues to SNS topics. AWS documentation has a basic example of the pattern here: https://aws.amazon.com/getting-started/hands-on/send-fanout-event-notifications/

Here's an example of what the CloudFormation configuration looks like (there's probably a CDK example out there too): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#aws-resource-sns-subscription--examples--Create_a_subscription_with_optional_attributes--yaml

Note the protocol set to `sqs`.

**Comment by cmcnicholas** [comment]
> > What would be the use case?
> 
> A common pattern, usually called "fanout", is to subscribe SQS queues to SNS topics. AWS documentation has a basic example of the pattern here: https://aws.amazon.com/getting-started/hands-on/send-fanout-event-notifications/
> 
> Here's an example of what the CloudFormation configuration looks like (there's probably a CDK example out there too): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#aws-resource-sns-subscription--examples--Create_a_subscription_with_optional_attributes--yaml
> 
> Note the protocol set to `sqs`.

Exactly this, I'm experiencing this on a project at the moment and have seen this used before in a few places, it's quite common for allowing resilient simplified async processing of independent pipelines e.g. 

![image](https://github.com/getlift/lift/assets/41394833/5e05ff07-330b-49b2-a04d-54a9b507fa5c)

**Comment by cmcnicholas** [comment]
I've had a stab at implementing this, see #344 

I would appreciate any help simplifying or helping to resolve the issue about having to use ARN strings instead of Refs.

**Comment by cmcnicholas** [comment]
sorry to chase up on this, after doing a little bit of digging I still can't find the "plugin way" to resolve refs in the linked PR e.g.

```yaml
constructs:
  ## adds a simple queue and unfiltered subscription
  my-queue:
    type: queue
    worker:
      handler: worker.handler
    subscriptions:
      - topic: !Ref MyTopic # this doesn't work
```

does anyone have any reference material for working with refs that need to be resolved dynamically with lift?
