### ISSUE TITLE
Could we have ability to export given sqs queue?

### ISSUE THREAD

**Issue by Setitch** [getlift/lift#268]
### Start from the Use-case

I have an issue when in one service i defined queue, but in service derived from it, i need access to one of the queues defined earlier. 
Would it be possible to add exporting options to the queue(arn mostly) so it would be used in other services?

The structure
```
service: name1
// here we include lift and make queues
```
```
service: name2
// here i would be able to import the queue and be able to use its address in lambdas defined in this file
```

### Implementation Idea

```
queueName:
   type: queue
   worker:
     timeout: 20
     handler: /file.handler
     role: SomeRole
   export:
     name: QueueExportedName
```

and then in other file, i would like to use Fn::ImportValue (or something) to access exported queue
