### ISSUE TITLE
Cannot get SPA's cname in httpApi.cors.allowedOrigins

### ISSUE THREAD

**Issue by zehao99** [getlift/lift#270]
### Description

When creating react single-page-app, `provider.httpApi.cors.allowedOrigins` cannot get the cname generated for CloudFront distribution of the app.
The output is `[object Object]`.
Seems like the value gets compiled before serverless update/create cloud formation resources.
However, queue's values can be referred to inside the `provider.environment` value.

### How to Reproduce

serverless.yml:

```
constructs:
  react:
    type: single-page-app
    path: "ui/build"
  msg-queue:
    type: queue
    worker:
      handler: queue/consumer.handler
      reservedConcurrency: 1

provider:
  httpApi:
    cors:
      allowCredentials: true
      allowedOrigins:
        - https://${construct:react.cname}
  environment:
     MSG_QUEUE_URL: ${construct:msg-queue.queueUrl}
```

Generated allowedOrigins is : `https://[object Object]`

### Additional Information

Version information:
```
"serverless-lift": "^1.20.2"
"serverless": "^3.22.0"
```
