### ISSUE TITLE
Add bucketPolicy and bucketName to storage construct

### ISSUE THREAD

**Issue by andynaguyen** [getlift/lift#272]
### Use Case

I'm currently using lift to create s3 storage buckets. I have two requests:
- Make it more convenient to name the bucket
- Enable bucket policy support

Currently, creating a separate bucket policy doesnt guarantee that the policy will be applied. Lift is creating its own default bucket policy from CDK, so if I create my own bucket policy as a separate resource, there will actually be two bucket policies created. From my understanding, only the first policy will apply to the bucket (which would be the default policy from CDK). To support bucket policies on storage constructs, we would need to call `addToResourcePolicy(statement)` (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3-readme.html#permissions)

### Example Config

```
constructs:
  my-bucket:
    type: storage
    encryption: kms
    extensions:
      bucket:
        Properties:
          BucketName: ${sls:stage}-${self:service}-my-bucket-${aws:region}

...

resources:
  Resources:
    MyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${construct:my-bucket.bucketName}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Principal:
                AWS:
                  - ${self:custom.externalDataRole}
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Join
                - "/"
                - - ${construct:my-bucket.bucketArn}
                   - "*"
            - Principal:
                AWS: ${self:custom.externalDataRole}
              Effect: Allow
              Action:
                - s3:ListBucket
              Resource: ${construct:my-bucket.bucketArn}

```

## Implementation Idea

Initial Implementation Idea.
```
constructs:
  my-bucket:
    type: storage
    encryption: kms
    name: ${sls:stage}-${self:service}-my-bucket-${aws:region}
    policyStatements:
      - Principal:
          AWS:
            - ${self:custom.externalDataRole}
        Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
        Resource: !Join
          - "/"
            - - ${construct:my-bucket.bucketArn}  # I don't this we'd be able to self-reference like this. 
            - "*"
      - Principal:
          AWS: ${self:custom.externalDataRole}
        Effect: Allow
        Action:
          - s3:ListBucket
        Resource: ${construct:my-bucket.bucketArn}
```

To avoid the self-reference issue. Since all s3 bucket resource policy requires that the resource is based on the arn itself, we can join implicitly to the bucket arn such that:
- no resource provided in construct = `Resource: ${bucket ARN}/`
- `Resource: "*"` = `Resource: ${bucket ARN}/*`
- `Resource: "prefix1"` = `Resource: ${bucketArn}/prefix1`

```
constructs:
  my-bucket:
    type: storage
    encryption: kms
    name: ${sls:stage}-${self:service}-my-bucket-${aws:region}
    policyStatements:
      - Principal:
          AWS:
            - ${self:custom.externalDataRole}
        Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
        Resource: "*" # will translate to ${bucketArn}/*
      - Principal:
          AWS: ${self:custom.externalDataRole}
        Effect: Allow
        Action:
          - s3:ListBucket
        # no Resource provided, will translate to the bucket's arn in CDK
```
