### ISSUE TITLE
Add user defined 'Cache-Control' header to CloudFront responses for assets

### ISSUE THREAD

**Issue by duswie** [getlift/lift#278]
### Start from the Use-case

It's best practise to serve static assets with a efficient cache policy:
https://web.dev/uses-long-cache-ttl/

This is especially relevant when using an asset build system with cache busting (dynamic asset names).
In this case I just want to set one Cache-Control header for all assets.

### Example Config

```
constructs:
  website:
    type: server-side-website
    assetsCachePolicyHeader: max-age=31536000

```

### Implementation Idea

A) CloudFront function:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-add-cache-control-header.html

or

B) CloudFront Response Header Policy (AWS::CloudFront::ResponseHeadersPolicy)
https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-responseheaderspolicy.html

Not sure which one performs better, but I think the response header policy is the 'cleaner' way.

I look forward to your feedback and would implement the feature if desired.

**Comment by jaulz** [comment]
I think it would be great if we could even extend it using ResponseHeaderPolicy and also pass options to define the strict transport security etc.

**Comment by duswie** [comment]
Thanks for your Feedback!
My current solution for custom response headers is as follows and work fine for me.
When I find time, I will try to implement it natively.

```yaml
resources:
    Resources:
        ResponseHeadersPolicyBuildAssets:
             Type: AWS::CloudFront::ResponseHeadersPolicy
             Properties:
                 ResponseHeadersPolicyConfig:
                     Name: AddCacheControlHeader
                     CustomHeadersConfig:
                         Items:
                             -   Header: Cache-Control 
                                 Override: false
                                 Value: max-age=31536000 
constructs:
    website:
        #...
        assets:
            '/build/*': public/build
        extensions:
            distribution:
                Properties:
                    DistributionConfig:
                        CacheBehaviors:
                            0:
                                ResponseHeadersPolicyId: !Ref ResponseHeadersPolicyBuildAssets
```
