### ISSUE TITLE
On Deployment Enable Reference to Output Variable

### ISSUE THREAD

**Issue by adam-kramer** [getlift/lift#279]
### Start from the Use-case

Currently when an SQS service is provisioned it auto generates a unique output variable which wouldn't be known prior to deployment. e.g. QueueNameB3FA2E83. We would like to reference the generated `https` endpoint in an environmental variable to consume within the deployed lambda functions of the same CF Stack. 

### Example Config

Ideally:

```
resources:
  Outputs:
    TheExactQueueNameIUsed:
      Description: Something to describe the queue
      Value: !GetAtt TheExactQueueNameIUsed.Url or .Endpoint
```

### Implementation Idea

In AWS CF we consume values from generated resources much like its described in the example config above. For example if I built a custom VPC Subnet and I wanted the generated `id` from that deployment as a named output I would write:

```
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZoneId: "usw2-az1"
      Tags:
        - Key: Name
          Value: my-public-subnet-1
```
and then in my serverless.yml file consume that value to Output.

```
resources:
  Outputs:
    PublicSubnet1:
      Description: VPC Public Subnet 1
      Value:
        Ref: PublicSubnet1
```
As you can see the use of the name `PublicSubnet1` was prescribed and referenced in the Outputs of that deployment for consumption either within its own stack or in other stacks.
