### ISSUE TITLE
Can not reference table generated by contruct

### ISSUE THREAD

**Issue by richard457** [getlift/lift#282]
### Description

Hi, I used to reference table like this 
```
EVENT:
    handler: EVENT.handler
    tracing: "false"
    events:
      - stream:
          type: "dynamodb"
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Table
              - StreamArn
          filterPatterns:
            - eventName: [INSERT]
         ``` 
but now I want to reference table in Fn::GetAtt: generated by construct how can I do that?

### How to Reproduce

Hi, I used to reference table like this 
```
EVENT:
    handler: EVENT.handler
    tracing: "false"
    events:
      - stream:
          type: "dynamodb"
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Table
              - StreamArn
          filterPatterns:
            - eventName: [INSERT]
         ``` 
but now I want to reference table in Fn::GetAtt: generated by construct how can I do that?
