### ISSUE TITLE
Excessive INSUFFICIENT_DATA -> OK from Queue alarms 

### ISSUE THREAD

**Issue by tomchiverton** [getlift/lift#292]
### Start from the Use-case

Our Queue do not get used 24/7, so every time a first request comes in after some period of inactivity, we get a `Subject: OK ..." email indicating

```
Alarm Details:
- Name:                       project-stage-functionAlarmExecutionsFailed-random
- Description:                Share step functions errors
- State Change:               INSUFFICIENT_DATA -> OK
- Reason for State Change:    Threshold Crossed: 1 datapoint [0.0 (01/02/23 08:40:00)] was not greater than the threshold (0.0).
```

### Example Config

```
constructs:
  foo:
    type: queue
    encryption: 'kmsManaged'
    alarm: us@domain.com
    worker:
      handler: module.foo
      vpc: ${self:custom.vpc}
```

### Implementation Idea

```
constructs:
  foo:
    type: queue    
    alarm: us@domain.com
      when_ok: false
```
