### ISSUE TITLE
Storage Construct - Invalid variable reference syntax for variable constructs:videos.bucketName

### ISSUE THREAD

**Issue by Chtiadrien** [getlift/lift#36]
Hello 👋

I'm currently testing Lift constructs and I'm trying to find a small use case for each constructs for my company needs.

I've deployed the "Storage" construct but then realize that I forgot the env variable for the bucket name. I added it and the `sls deploy` command fail:

```
Invalid variable reference syntax for variable constructs:videos.bucketName. You can only reference env vars, options, & files. You can check our docs for more info.
```

Here is my files, I'm keeping them as simple as possible for demo purpose:

```yaml
# serverless.yml
service: ugc-upload # user-generated-content, small project to accept videos from an user

provider:
  name: aws
  profile: superadmin # multiple account in my credentials
  region: eu-west-2 # for reasons
  runtime: provided.al2
  lambdaHashingVersion: 20201221

plugins:
  - serverless-lift
  - ./vendor/bref/bref

constructs:
  videos:
    type: storage

functions:
  get-signed-url:
    handler: src/GetSignedUrlHandler.php
    layers:
      - ${bref:layer.php-80}
    events:
      - httpApi: "GET /"
    environment:
      BUCKET_NAME: ${constructs:videos.bucketName}
```

```json
# package.json
{
  "devDependencies": {
    "serverless": "^2.46.0",
    "serverless-lift": "^1.1.0"
  }
}
# Got this from `npm i --save-dev serverless serverless-lift`
```

```json
 # composer.json
{
    "require": {
        "bref/bref": "^1.2",
        "async-aws/s3": "^1.9",
        "azjezz/psl": "^1.7"
    }
}
# Got this from `composer require bref/bref async-aws/s3 azjezz/psl`
```

```php
# src/GetSignedUrlHandler.php
<?php

require dirname(__DIR__) . '/vendor/autoload.php';

use AsyncAws\S3\Input\PutObjectRequest;
use AsyncAws\S3\S3Client;
use Bref\Context\Context;
use Bref\Event\Http\HttpHandler;
use Bref\Event\Http\HttpRequestEvent;
use Bref\Event\Http\HttpResponse;
use Psl\Json;
use Psl\SecureRandom;

class GetSignedUrlHandler extends HttpHandler
{
    public function handleRequest(HttpRequestEvent $event, Context $context): HttpResponse
    {
        $client = new S3Client();

        $input = new PutObjectRequest(
            [
                "Bucket" => $_ENV["BUCKET_NAME"],
                "Key" => SecureRandom\string(11) . ".png",
            ]
        );

        $signedUrl = $client->presign($input);

        return new HttpResponse(
            Json\encode(["signed-url" => $signedUrl]),
            ["Content-Type" => "application/json"],
        );
    }
}

return new GetSignedUrlHandler();
```

The complete output of `sls deploy` : 

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Approached unrecognized configuration variable sources: "constructs".
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
 
 Serverless Error ----------------------------------------
 
  Invalid variable reference syntax for variable constructs:videos.bucketName. You can only reference env vars, options, & files. You can check our docs for more info.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.46.0 (standalone)
     Plugin Version:            5.4.0
     SDK Version:               4.2.3
     Components Version:        3.12.0

```
