### ISSUE TITLE
Specify Visibility Timeout for SQS other than 6 * function timeout

### ISSUE THREAD

**Issue by johncourt** [getlift/lift#361]
### Start from the Use-case

SQS allows visibility timeout up to 12 hours.

To achieve this I need to set the worker timeout to 2 hours so lift can calculate 6 * 2 = 12 hours. But I want my lambda to time out after a few seconds not 2 hours, wait 12 hours and try again.

### Example Config

From the docs:

```
constructs:
    my-queue:
        # ...
        worker:
            handler: src/worker.handler
            memorySize: 512
            timeout: 10
```

### Implementation Idea

Add an attribute called queueTimeout which overrides the default 6 * worker timeout behaviour

**Comment by johncourt** [comment]
Great project by the way - avoids a significant limitation with serverless

**Comment by tampueroc** [comment]
You can configure the SQS Queue VisibilityTimeout Property by adding it as an extension on the construct!
```
constructs:
    my-queue:
        type: queue
        worker:
            handler: src/worker.handler
        extensions:
            queue:
                Properties:
                    VisibilityTimeout: 43,200 # 12 Hours
```
Sources:
- https://github.com/getlift/lift/blob/master/docs/queue.md#extensions
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-visibilitytimeout
