### ISSUE TITLE
Node 10 compatibility ("flat is not a function")

### ISSUE THREAD

**Issue by Aikoze** [getlift/lift#38]
Hello :hand: 

I have probleme using  `<construct>:upload` , I'm trying to deploy my landing page using the configuration said on documentation

I run :  
`serverless landing:upload`

With this config bellow :

```
constructs:
    landing:
        type: static-website
        path: landingPage

```

And this error append

![image](https://user-images.githubusercontent.com/23453566/122402838-25169d00-cf7e-11eb-83da-820af7f40593.png)

Seems like i don't have permission but I'm also using serverless to deploy my API using bref.sh with the same IAM role.
