### ISSUE TITLE
Serverless V4: Provider construct is not supported

### ISSUE THREAD

**Issue by franzs97** [getlift/lift#394]
### Description

After updating to serverless v4 it throws an error on deployment/validation:

✖ Provider construct is not supported
Error: Provider construct is not supported

### How to Reproduce

```yaml


[...]

provider:
  name: aws
  region: eu-central-1
  [...]
  environment:
    SERVICE_NAME: ${self:service}
    REGION_NAME: ${aws:region}
    TABLE_NAME: ${construct:MyTable.tableName}  # this throws the error


constructs:
  MyTable:
    type: database/dynamodb-single-table
    extensions:
      table:
        Properties:
          TableName: ${self:service}-MyTable
```

### Additional Information

The serverless.yaml still worked in v3.
