### ISSUE TITLE
'${construct:myQueueConstruct.dlqArn}' can't be resolved in functions.events.sqs

### ISSUE THREAD

**Issue by lynxSven** [getlift/lift#404]
### Description

I true to use the dlqArn of a construct to send the errors to another lambda function.
When i try to use it in functions.events.sqs I get this error message when I try to deploy
Configuration error at 'functions.handleError.events.0.sqs': must match pattern "^arn:"

When I try to use this placeholder in a ENVIRONMENT of the lambda function, like in the queue.md example, it works fine.

Maybe the preprocessor can't handle this placeholder?

### How to Reproduce

```yaml
...
    handler: 'pathToHandler.handler'
    events:
       - sqs: '${construct:contractData.dlqArn}'
 ...
```
