### ISSUE TITLE
CORS Issue for Javascript Files

### ISSUE THREAD

**Issue by michaelaguiar** [getlift/lift#411]
### Description

I am deploying a Laravel app and have my assets going to the S3 bucket. This works great for both css and images, but for Javascript I keep getting a CORS error:

`Origin https://XXXX.execute-api.us-west-2.amazonaws.com is not allowed by Access-Control-Allow-Origin. Status code: 200`

### How to Reproduce

Here is what I have in my serverless.yml file

```yaml
constructs:
  website:
    type: server-side-website
    assets:
      "/build/*": public/build
      "/images/*": public/images
      "/favicon.ico": public/favicon.ico
      "/robots.txt": public/robots.txt
``` 

### Additional Information

I noticed that if I change the `Origin Request Policy` to `CORS-S3Origin`, it fixes the issue. How can I set this automatically in my serverless.yml file, OR what is another way to get my .js files to load?
