### ISSUE TITLE
Permissions for queue construct

### ISSUE THREAD

**Issue by Pigius** [getlift/lift#47]
Hello, thank you for the development of the Lift plugin, it's so awesome, I hope it will support more use cases in the near future. I especially like it as a Ruby developer, as AWS CDK does not support it at all 😞 .

## Background:

Yesterday I've submitted the [PR](https://github.com/serverless/examples/pull/620) for the Serverless Framework example (SQS + DynamoDB). I've used the `queue construc`t for the example which is awesome.

However, during the implementation, I've crossed upon one problem, not sure whether is due to the construct, or maybe due to my lack of knowledge in some of the aspects of Serverless Framework.

## Problem

Within the  [permissions](https://github.com/getlift/lift/blob/master/docs/queue.md#permissions) section, we can see the information about:

> By default, all the Lambda functions deployed in the same serverless.yml file will be allowed to push messages into the queue.

> In the example below, there are no IAM permissions to set up: myFunction will be allowed to send messages into my-queue.

```yml
constructs:
    my-queue:
        type: queue
        # ...

functions:
    myFunction:
        handler: src/publisher.handler
        environment:
            QUEUE_URL: ${construct:my-queue.queueUrl}
```

This is quite nice, as I do not need to provide IAM statements within the `serverless.yml`.

However, when I've added another resource, which is DynamoDB in my case, and added the IAM statements:

```yml
iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - !GetAtt Table.Arn
 ```
After the deployment, the Lambda function for the `myFunction` will not have permissions to access the SQS anymore. So to make it work I need to add to the above iam role statements:
```yml
        - Effect: Allow
          Action:
             - sqs:SendMessage
          Resource: ${construct:lotteryQueue.queueArn}
```

Not sure, whether is a bug or not. 🤔

**Comment by t-richard** [comment]
I think this is because Lift uses the now deprecated `provider.iamRoleStatements` to add permissions and Serverless framework ignores it if `provider.iam.role.statements` is set like in your case.

@Pigius Could you confirm using the following is working as expected ?

```
provider:
    iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - !GetAtt Table.Arn
```
