### ISSUE TITLE
[Static website] Build websites with environment variables

### ISSUE THREAD

**Issue by mnapoli** [getlift/lift#62]
Use case:

I want to build my static website (e.g. `npm run build`) and pass the serverless API URL to the static website as an environment variable.

Possible solution:

```yaml
constructs:
  landing:
    type: static-website
    path: dist
    build:
      script: 'npm run build'
      environment:
        VUE_APP_API_URL: !GetAtt HttpApi.ApiEndpoint
```

The `build` option is optional:

- if undefined, the user has to build the website before `serverless deploy`
- if set, the script will be run during `serverless deploy` (after the CloudFormation deployment, before uploading the static website to S3)

Challenge: the `!GetAtt HttpApi.ApiEndpoint` would probably not be resolved by Serverless/Lift since this isn't a variable. So my example above isn't really working, yet this is probably the most common use case. How can we solve this?

**Comment by M1ke** [comment]
As far as I can see this would work. I am basing it off the example I have for achieving this away from Lift: https://github.com/M1ke/serverless-payments/blob/master/bin/deploy-dev-front

So in this script I:

* Source the required `.env.*` file (which `sls` can do for me with `useDotEnv` declared)
* Pull the API url out of the serverless outputs (which this example is doing using `GetAtt`)
* Pass my `REACT_` variables to the build (which this does by repeating them in `environment:`)

Only question is, what's the correct pattern for the API URL of 

```
functions:
  something:
    ... stuff ...
    events:
      - httpApi: '*'
```
