### ISSUE TITLE
DLQ URL/ARN not available

### ISSUE THREAD

**Issue by M1ke** [getlift/lift#63]
When trying to use a DLQ in another component via:

```
destinations:
      onFailure: ${construct:queue.dlqUrlOutput}
```

I am getting the error:

```
Resolution error: ${construct:queue.dlqUrlOutput} does not exist. Properties available on ${construct:queue} are: queueUrl, queueArn.
```

However the below linked line seems to suggest this does get output:

https://github.com/getlift/lift/blob/25192e628a1ed25c2b1beb5866c289c1237f2341/src/constructs/Queue.ts#L140

**Comment by M1ke** [comment]
Actually having re-read this even if it was available it wouldn't work as I'd need the ARN. But either way, this looks like both should be available.

**Comment by t-richard** [comment]
When looking for available variables, you have too look at `references`

https://github.com/getlift/lift/blob/25192e628a1ed25c2b1beb5866c289c1237f2341/src/constructs/Queue.ts#L154

Outputs are just the Cloudformation stack outputs but are not directly related to what's available in Lift variables.

But yeah, that could be cool to have those too.

What is the use case here ?

**Comment by mnapoli** [comment]
Hey, I think your use case makes sense, but I'm not sure it should be solved by reusing the DLQ from the queue component to be honest.

To me, it seems like you rather need a DLQ on the Lambda handling eventbridge messages, right?

Maybe it would make sense to have a (production-ready) "event handler" construct for handling eventbridge messages? That construct could include all the default config for production scenarios, like retries, DLQ, etc.

Here is an illustration:

Before:

```yaml
provider:
  ...
  eventBridge:
    useCloudFormation: true

functions:
  myfunc:
    handler: index.handler
    events:
      - eventBridge:
          eventBus: ...
          pattern: ...
          inputTransformer: ...
      - eventBridge:
          eventBus: ...
          pattern: ...
          inputTransformer: ...
    destinations:
      onFailure: ${construct:queue.dlqUrlOutput}
```

After:

```yaml
constructs:

  myfunc:
    type: event-handler
    handler: index.handler
    events:
      # only eventbridge events allowed here
      - eventBridge:
          eventBus: ...
          pattern: ...
          inputTransformer: ...
      - eventBridge:
          eventBus: ...
          pattern: ...
          inputTransformer: ...
```

That will automatically configure a SQS dead letter queue for this handler.

Just like with queues, the construct could provide the commands:

```sh
serverless myfunc:failed
# list failed messages from the dlq

serverless myfunc:failed:retry
# retry failed messages
```

What do you think?
