### ISSUE TITLE
server-side-website - missing default page for cdn

### ISSUE THREAD

**Issue by piolet** [getlift/lift#94]
In Server-side-website, we can configure the error page with :
```
constructs:
    website:
        # ...
        errorPage: error500.html
```
But we can't set the CDN's default page, like this :
```
constructs:
    website:
        # ...
        defaultPage: index.html
```

In my case, for example, index.html is added in my assets (it's a fully static page), but if i go to the page https://mydomain.com i redirect to the lambda mangement. If i go directly to https://mydomain.com/index.html, it's ok, but not really top.

What do you think ?

**Comment by t-richard** [comment]
The server-side website is targeted at frameworks like Ruby on Rails, Symfony/Laravel, Django, Express, etc where the HTML rendering would be done server-side (with erb, twig/blade, DTL/Jinja, ejs/nunjucks, etc).

What you are willing to do looks like the [static website construct](https://github.com/getlift/lift/blob/master/docs/static-website.md), to run a static website generated by Jekyll or Hugo for example. Or Single page apps built with Vue.js or React.

Can you tell us a bit more about the use case here ?

**Comment by piolet** [comment]
In my case, some page are static (full html) and some other are dynamic (php rendering).
All is ok, except for home page, my index.html. It's not a SPA.

**Comment by t-richard** [comment]
This is somewhat out of scope of this construct (at least for now). 

**Maybe** you could trick the construct by doing something like

```yaml
constructs:
    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
            '/': index.html
```

or

```yaml
constructs:
    website:
        type: server-side-website
        assets:
            '/css/*': public/css
            '/js/*': public/js
            '': index.html
```

This is from the top of my head, not sure it works but might be worth a try.
