### ISSUE TITLE
Extend construct to also accept "image" instead of just "handler" for docker support

### ISSUE THREAD

**Issue by StianHanssen** [getlift/lift#99]
I was wondering if it would be possible to extend the "construct" entry in serverless.yml to also accept docker images?

For example, I can deploy a docker image in serverless like this:
```yaml
provider:
  name: aws
  ecr:
    images:
      my-docker-image:
        path: ./

functions:
  my-function:
    image:
      name: my-docker-image
```

And I would love to use lift to add additional resources around it. However, this is not currently allowed:
```yaml
provider:
  name: aws
  ecr:
    images:
      my-docker-image:
        path: ./

constructs:
  my-queue:
    type: queue
    worker:
      image:
        name: my-docker-image
```

My hope is that this is just a constraint put on the serverless.yml, and that lift can fall back on serverless functionality to deploy the images. That said, I appreciate that I don't have overview of the work required at all. 

Would be great to hear your thoughts on this request!
